version: "3.9"

services:
  reverse-proxy:
    image: caddy:2
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mm-ui
      - mm-api
      - keycloak
    networks: [internal]

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks: [internal]

  kc-postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${KC_DB_NAME}
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - kc-pg-data:/var/lib/postgresql/data
    networks: [internal]

  keycloak:
    image: ${KEYCLOAK_IMAGE}
    command: >
      start --hostname-strict=false --proxy=edge
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: kc-postgres
      KC_DB_URL_DATABASE: ${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    networks: [internal]
    depends_on: [kc-postgres]

  mm-api:
    image: ${MM_API_IMAGE}
    environment:
      ACTIVE_PROFILE: prod
      DB_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${PROTOCOL}://${AUTH_HOST}/realms/market-mingle
    expose:
      - "8088"
    networks: [internal]
    depends_on: [mysql, keycloak]

  mm-ui:
    image: ${MM_UI_IMAGE}
    expose:
      - "80"
    networks: [internal]
    depends_on: [mm-api]

networks:
  internal:

volumes:
  mysql-data:
  kc-pg-data:
  caddy-data:
  caddy-config:
